services:
  mongodb:
    image: mongo:7-jammy

    container_name: mongodb

    ports:
      - "27007:27017"

    volumes:
      - ./mongodata:/data/db

    networks:
      - backend

    restart: always


networks:
  backend:
