name: Test Multiple Python Versions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest   
    strategy:
      matrix:
        python-version: [3.11.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make install

      - name: Format code with Python Black
        run: |
          make format

      - name: Lint with pylint
        run: |
          make lint

      - name: Test with pytest   
        run: |
          make test

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t momenamuhammed/time_series_forecasting:latest .

      - name: Push image to Registry (docker hub )
        run: |
          docker push momenamuhammed/time_series_forecasting:latest

      - name: deploy with AWS ESC
        run: |
          make deploy
